
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: myblog_development

test:
  <<: *default
  database: myblog_test

production:
  <<: *default
  database: myblog_production
  username: myblog
  password: <%= ENV['MYBLOG_DATABASE_PASSWORD'] %>
