# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa5ee5b8f2f379042a120bcdfec5ac43ab89f20e96f2441d1dc18b7b0ae00bdcbbcd5300f29e00a40891d6e8cecd6abae63cfacae19b6d49d3d6d5fafc0e0e17

test:
  secret_key_base: 3abfe3310032b977c0b25b6adecd80c2e0c1cb2f7338898f99d6ec3b1eba9647f7ee751ca7f4cad621d2a030ca013e505726349853be91f9fee919c22c9b57bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
