default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: parking_development

test:
  <<: *default
  database: parking_test

production:
  <<: *default
  database: parking_production
  username: parking
  password: <%= ENV['PARKING_DATABASE_PASSWORD'] %>
